twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        contact_address: '20 rue marcelin berthelot'
        contact_city: 'Alfortville'
        contact_email: 'abbassi.hassen23@gmail.com'
        contact_phone: '06.73.06.29.04'
        contact_zip: '94140'
        copyright: 'Copyright © 2021 - Abbassi Hassen'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
